### PR TITLE
fix: azure sdk httpclient instrumentation issue

### PR DESCRIPTION
**Pull request by ekremney**
## Description

Fixes `ASSETS-4291`

node-openwhisk-newrelic was having issues when used with aio-lib-state

was patched by commenting out this line: https://github.com/adobe/node-openwhisk-newrelic/blob/11c06eb702aadd31886b44ab731f34e5f010ffad/lib/probe/http-client.js#L250

Fixes # (issue)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by tmathern — APPROVED** [review]
I saw you checked `My change requires a change to the documentation.`, but I didn't see any change to documentation needed (nor a document change)?

**Comment by tmathern** [comment]
> @tmathern that was a mistake. This is just a bugfix, no documentation change needed. Can I just merge this one now?

Do you know the semantic release rules we follow to trigger a release?

**Comment by tmathern** [comment]
> @tmathern do you have any other rules than adding a `BUGFIX-RELEASE` prefix to commit message?

No. That's it. 
LGTM. Don't forget to add the message so this gets released (usually we `squash and merge`)!

**Comment by alexkli** [comment]
@ekremney @tmathern I think there is a problem. IIUC this PR entirely removes the response size metric for chunked encoding (with no content length headers). Unless I am missing something, the new unit tests do not test for the metric and the one test case that covered it was removed.

This will have a negative impact on our production metrics. Please revert and then we discuss the right solution.

**Pull request merged**
